start "" "c:\PortableApps\PortableApps.com\PortableAppsPlatform.exe"
start "" "C:\Program Files (x86)\Microsoft Office\root\Office16\OUTLOOK.EXE"
start "" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
start "" "C:\green\GoldenDict\GoldenDict.exe"
start "" "C:\green\ProxySwitcher.-.v3.6.3\ProxySwitcher.exe"
start "" "C:\Program Files\Everything\Everything.exe"